name: Deploy

on:
  push:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            verification-licences
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: verification-licences:latest
          labels: verification-licences
      - run: docker images
      - run: docker save verification-licences:latest > image.tar
      - name: Upload image as artifact
        uses: actions/upload-artifact@master
        with:
          name: image
          path: ./image.tar

  deploy:
    needs: [ build-docker-image ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download image
        uses: actions/download-artifact@master
        with:
          name: image
          path: .
      - name: List files
        run: ls -al
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "image.tar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
